parent_config: ../.swiftlint.yml

disabled_rules:
  - force_cast
  - force_unwrapping
  - force_try
  - implicitly_unwrapped_optional 

# This shouldn't be necessary, but there's a but when a rule is enabled in a parent
# config and configured in a child config.
# Fixed in late March 2024 and merged to main, but not yet in a release
# https://github.com/realm/SwiftLint/pull/4864
# BEGIN FIX

opt_in_rules:
  - file_header
  - file_name

# END FIX

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  SLAPTests
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/

type_name:
  allowed_symbols: ["_"]

# Reset this the suffix_pattern (inherited) b/c it gets mad
# about the _ in Foo_ViewModelTests.swift
file_name:
  suffix_pattern: ""
